### ISSUE TITLE
How to connect the ESP32 to the Battery

### ISSUE THREAD

**Issue by berni2288** [zivillian/esp32-pylontech#4]
Hey there!

I just found your project and the code seems quite clean to me.
Can you tell me how to connect the ESP32 to the battery maybe?

Does it use the Console port or the RS485 port? Thanks!

**Comment by zivillian** [comment]
Thanks! This Project implements the RS485 protocol, I've connected the ESP to the master battery with an RS485 to TTL Level converter. The pin assignment is described in the user manual.

**Comment by berni2288** [comment]
Danke dir!

Do you mean this user manual here?
To be honest, I'm not quite sure what I should do with CAN-H, CAN-L and CAN-GND listed in the RS485 column, the table is confusing.

I assume I only need Pins 6-8 (GND, 485A, 485B), can you confirm? :) 

![image](https://user-images.githubusercontent.com/1029328/215468347-3881e1bb-bb5c-468c-8cd6-73fe9c277cde.png)

**Comment by zivillian** [comment]
Yes, that's how I connected it.

**Comment by zivillian** [comment]
There are two types of CAN Port - one is a combined one for all modules and the CAN PINs on the RS485 Port are only for this single module.

**Comment by berni2288** [comment]
Thanks for the answer, I'm closing this issue since I got all infos I need.
